#+BEGIN_COMMENT
.. title: Copy paste from Emacs nw to other application
.. slug: copy-paste-from-emacs-nw-to-other-application
.. date: 2019-03-04 23:56:54 UTC+01:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

Their is one plugin to use make it possible: [[https://elpa.gnu.org/packages/xclip.html][xclip]]

This plugin uses xclip/xsel on Linux, if both of them are not exist, it uses emacs `make-frame-on-display`.
They require `DISPLAY` to be set correctly. In my case, I use putty to login the server then use `emacsclient -nw`
to connect to the emacs daemon, I have no xclip/xsel installed.
Some times the `DISPLAY` was not set correctly when multiple ssh clients connect to the server.

Follow steps can make the copy/paste works again.

#+BEGIN_SRC lisp
(setq xclip--hidden-frame nil)
(setenv "DISPLAY" "localhost:12.0")
#+END_SRC


To reset the hidden frame when new emacs client connect to deamon, write an funciton like:
#+BEGIN_SRC lisp
(defun bl-update-display (display)
  "Reset the DISPLAY in EMACS client and kill the xclip hidden frame if exist."
  (setenv "DISPLAY" display)
  (delete-frame xclip--hidden-frame t)
  (setq xclip--hidden-frame nil)
  )
#+END_SRC

Then add alias to emacs client like:
#+BEGIN_SRC sh
alias ecnw="emacsclient -nw -c --eval \"(bl-update-display \\\"$DISPLAY\\\")\""
#+END_SRC

*NOTE*: Limitation of this workaround, if more than one emacs client connect to the deamon, only one client work properly.

